import { normalizeCustomPermissionDimensions } from "./utils";

export const defaultUiSettings = {
  inspectorWidth: 320,
  restoreWorkspace: true,
  confirmClose: true,
  autoProbe: true,
  manualModels: [],
  aiProviders: [],
  defaultModelId: "",
  recentLimit: "10",
  editor: "VS Code",
  theme: "Dark",
  accent: "Blue",
  density: "Comfortable",
  uiTextSize: "Default",
  codeTextSize: "13",
  timestampFormat: "Relative",
  language: "English (en-US)",
  workerCount: "2",
  retries: "1",
  planApproval: "Always ask",
  blockOnFailingValidation: true,
  requireIndependentReviewer: true,
  integrationPolicy: "Manual",
  concurrencyLimit: "2",
  allowRiskOverrides: false,
  requireApprovalNetwork: true,
  requireApprovalPackages: true,
  customPermissionDimensions: normalizeCustomPermissionDimensions(),
  pushPolicy: "Ask each time",
  inAppNotif: true,
  systemNotif: true,
  soundNotif: false,
  notifPlanApproval: true,
  notifAgentFailure: true,
  notifBlockedTask: true,
  notifReviewComplete: true,
  notifValidationComplete: false,
  notifIntegrationReady: true,
  retention: "30 days",
  reducedMotion: false,
  highContrastFocus: false,
  screenReaderAnnouncements: true,
  defaultProjectDirectory: "",
};
