import type { Locale } from "@agentflow/localization";
import type { createTypedBridge } from "@agentflow/desktop-bridge";

export type PermissionDimensionsInput = Record<string, unknown>;
export type WorkflowPayload = Record<string, unknown> & {
  text?: string;
  permissionRequest?: Record<string, unknown>;
};
export type PatchSetSummary = {
  id: string;
  taskId: string;
  sequence: number;
  changedFiles: string[];
  diffArtifactId: string;
  resultCommit: string;
  reviewState: string;
  baseCommit?: string;
};
export type ReviewSummary = {
  id: string;
  taskId: string;
  verdict: string;
  independent?: boolean;
};
export type FindingSummary = {
  id: string;
  severity: string;
  category?: string;
  message: string;
  file?: string;
  line?: number;
};
export type ChangeRequestSummary = {
  id: string;
  state: string;
  specificationRevisionId?: string;
  integrationBranch?: string;
  baseCommit?: string;
};
export type ProjectSummary = {
  id: string;
  repositoryPath: string;
  debugCommand?: string;
  defaultBranch?: string;
};
export type RuntimeStatus = Record<string, unknown> & {
  settings?: Record<string, unknown>;
  tasks?: Array<{
    id: string;
    key: string;
    title: string;
    state?: string;
    dependencyIds?: string[];
  }>;
  conversations?: Array<{ id: string }>;
  runs?: Array<{
    id: string;
    conversationId?: string;
    taskId?: string;
    role?: string;
    state?: string;
    completedAt?: string;
  }>;
  events?: Array<{
    conversationId?: string;
    changeRequestId?: string;
    type?: string;
    payload?: unknown;
  }>;
  projects?: ProjectSummary[];
  permissions?: Array<{ status?: string }>;
  resumeAvailableRunIds?: string[];
  patchSets?: PatchSetSummary[];
  reviews?: ReviewSummary[];
  findings?: FindingSummary[];
  changeRequests?: ChangeRequestSummary[];
  workspaces?: Array<{ taskId: string; path?: string }>;
  validations?: Array<{ taskId: string; status?: string }>;
};
export type TaskDisplayItem = {
  taskId: string;
  id: string;
  title: string;
  dependencies: string[];
  assignedAgent?: string;
  worktree?: string;
  validation?: string;
  review?: string;
  status: string;
  tone: string;
};
export type RunDisplayItem = {
  name: string;
  role: string;
  detail: string;
  time: string;
  tone: string;
};
export type RoutingDecisionSummary = {
  matchedRule?: string;
  reason?: string;
  selected?: { adapterId: string; profileId?: string };
  rejectedCandidates?: string[];
};
export type RepositoryStatusSummary = {
  branch: string;
  head: string;
  changedFiles: string[];
  unifiedDiff?: string;
};
export type SettingsSection = {
  id: string;
  key: string;
  icon: React.ElementType;
};
export type TimelineMessage = {
  id: string;
  role: string;
  text: string;
  streaming?: boolean;
  kind?: string;
  activity?: {
    category?: "tool" | "command" | "workflow";
    status?: string;
    title?: string;
    detail?: string;
  };
};
export type DiffViewerProps = {
  content: string;
  search: string;
  onSearch: (value: string) => void;
  viewMode: string;
  onViewMode: (value: string) => void;
  findings: Array<{ line?: number }>;
  locale: Locale;
};
export type PlanApprovalCardProps = {
  onApprove: () => void;
  onRequestChanges: () => void;
  onOpenPlan: () => void;
  labels: {
    planReady: string;
    requirements: string;
    tasks: string;
    structureChanges: string;
    yes: string;
    no: string;
    risk: string;
    openPlan: string;
    requestChanges: string;
    approveAndRun: string;
  };
  locale?: Locale;
  specification: { requirements: unknown[]; structureChanges: unknown[]; risk: string };
  tasks: Array<{ id: string; dependencyIds?: string[] }>;
};
export type PermissionRequest = {
  permission?: { requested?: string };
  permissionRequest?: PermissionRequest;
  requestedProfile?: string;
  command?: string;
  workingDirectory?: string;
  reason?: string;
};
export type PermissionRequestCardProps = {
  onResolve: (decision: string) => void;
  request?: PermissionRequest | null;
  locale?: Locale;
};
export type UiSettings = {
  theme: string;
  accent: string;
  language: string;
  workerCount: string;
  restoreWorkspace: boolean;
  confirmClose: boolean;
  autoProbe: boolean;
  manualModels: Array<{
    adapterId: string;
    providerId: string;
    modelId: string;
    name: string;
  }>;
  aiProviders: Array<{
    id: string;
    name: string;
    endpoint: string;
    apiKey: string;
    model?: string;
    models?: string[];
    apiVersion?: string;
  }>;
  defaultModelId?: string;
  recentLimit: string;
  defaultProjectDirectory: string;
  editor: string;
  density: string;
  uiTextSize: string;
  codeTextSize: string;
  timestampFormat: string;
  retries: string;
  planApproval: string;
  blockOnFailingValidation: boolean;
  requireIndependentReviewer: boolean;
  integrationPolicy: string;
  concurrencyLimit: string;
  allowRiskOverrides: boolean;
  requireApprovalNetwork: boolean;
  requireApprovalPackages: boolean;
  customPermissionDimensions: Record<string, unknown>;
  pushPolicy: string;
  inAppNotif: boolean;
  systemNotif: boolean;
  soundNotif: boolean;
  notifPlanApproval: boolean;
  notifAgentFailure: boolean;
  notifBlockedTask: boolean;
  notifReviewComplete: boolean;
  notifValidationComplete: boolean;
  notifIntegrationReady: boolean;
  retention: string;
  reducedMotion: boolean;
  highContrastFocus: boolean;
  screenReaderAnnouncements: boolean;
  inspectorWidth?: number;
};
export type RuntimeAdapterProfile = {
  id?: string;
  adapterId: string;
  name?: string;
  status?: string;
  version?: string;
  diagnostic?: string;
};
export type RuntimeModel = {
  id: string;
  adapterId: string;
  providerId?: string;
  providerModelId?: string;
  name: string;
  cliDefault?: boolean;
  verified?: boolean;
  capabilities?: string[];
};
export type SettingsRuntimeData = {
  adapterIds?: string[];
  profiles?: RuntimeAdapterProfile[];
  models?: RuntimeModel[];
  projects?: Array<{ id: string; defaultBranch?: string }>;
  dataDirectory?: string;
};
export type SettingsContentProps = {
  section: string;
  settings: UiSettings;
  set: (key: keyof UiSettings, value: unknown) => void;
  locale?: Locale;
  runtimeData?: SettingsRuntimeData | null;
  activeProject?: string;
  onProbe: () => void;
  onExportDiagnostics: () => void;
  onResetLayout: () => void;
  onResetSettings: () => void;
  onChooseDefaultProjectDirectory: () => void;
};
export type BridgeApi = ReturnType<typeof createTypedBridge>;
export type ComposerProps = {
  locale: Locale;
  openMenu: string | null;
  setOpenMenu: (value: string | null) => void;
  mode: string;
  setMode: (value: string) => void;
  permission: string;
  setPermission: (value: string) => void;
  currentModel: { id: string; label: string };
  model: string;
  modelGroups: Array<{
    id: string;
    label: string;
    models: Array<{
      id: string;
      label: string;
      sub: string;
      vision?: boolean;
      model: { providerModelId?: string };
    }>;
  }>;
  hasAuto: boolean;
  selectModel: (modelId: string) => void;
  contextAttachments: string[];
  setContextAttachments: React.Dispatch<React.SetStateAction<string[]>>;
  attachContextFiles: () => Promise<void>;
  composerRef: React.RefObject<HTMLTextAreaElement>;
  composerText: string;
  setComposerText: (value: string) => void;
  sendMessage: () => void;
  sending: boolean;
  stopActiveRun: () => Promise<void>;
  bridge: BridgeApi | null;
  runtimeConversationId: string | null;
  runtimeState: string;
  failedRunId: string | null;
  retryFailedRun: (resume: boolean) => Promise<void>;
  runtimeData: RuntimeStatus | null;
};
export type ConversationSidebarProps = {
  sidebarOpen: boolean;
  locale: Locale;
  labels: Record<string, string>;
  openMenu: string | null;
  toggleMenu: (name: string) => void;
  setOpenMenu: (value: string | null) => void;
  project?: { name?: string } | null;
  projectList: Array<{ id: string; name: string; branch?: string; convCount?: number }>;
  activeProject: string | null;
  setActiveProject: (id: string) => void | Promise<void>;
  openProject: () => Promise<void>;
  canOpenProject: boolean;
  openProjectUnavailableReason?: string;
  conversationSearchRef: React.RefObject<HTMLInputElement>;
  conversationQuery: string;
  setConversationQuery: (value: string) => void;
  newConversation: () => Promise<void>;
  conversationFilters: Array<[string, string, React.ComponentType<Record<string, unknown>> | null]>;
  conversationFilter: string;
  setConversationFilter: (value: string) => void;
  visibleConversations: Array<{
    id: string;
    title: string;
    pinned?: boolean;
    statusTone?: string;
    status?: string;
    time?: string;
  }>;
  runtimeConversationId: string | null;
  selectConversation: (id: string) => void;
  togglePinnedConversation: (id: string) => void;
  setSettingsOpen: (value: boolean) => void;
};
export type VirtualTimelineProps = {
  messages: TimelineMessage[];
  onCopy: (text: string) => Promise<void>;
  copyLabel?: string;
  jumpLabel?: string;
  timelineLabel?: string;
  locale?: Locale;
};
export type InspectorPanelProps = {
  inspectorOpen: boolean;
  tabs: string[];
  tab: string;
  setTab: React.Dispatch<React.SetStateAction<string>>;
  locale: Locale;
  bridge: BridgeApi | null;
  runtimeChangeRequestId: string | null;
  integrateApproved: () => Promise<void>;
  preparePullRequest: () => Promise<void>;
  workflowPhase: string;
  workflowProgress: number;
  completedTaskCount: number;
  displayTasks: TaskDisplayItem[];
  displayReviews: ReviewSummary[];
  currentModel: { id: string; label: string };
  effectivePermission: { id: string; label: string };
  currentChangeRequest: ChangeRequestSummary | undefined;
  currentRoutingDecision: RoutingDecisionSummary | undefined;
  repositoryStatus: RepositoryStatusSummary | null;
  runtimeData: RuntimeStatus | null;
  runReadyTasks: () => Promise<void>;
  runTask: (taskId: string) => Promise<void>;
  displayRuns: RunDisplayItem[];
  displayPatchSets: PatchSetSummary[];
  artifactContent: { content?: string } | null;
  openArtifact: (artifactId: string) => Promise<void>;
  openArtifactId: string | null;
  runValidation: (patchSetId: string) => Promise<void>;
  startReview: (patchSetId: string) => Promise<void>;
  artifactLoading: boolean;
  artifactSearch: string;
  setArtifactSearch: (value: string) => void;
  artifactViewMode: string;
  setArtifactViewMode: (value: string) => void;
  displayFindings: FindingSummary[];
  sendFindingsToFixer: () => void;
  blockingFindingsCount: number;
  patchSetsAwaitingReview: PatchSetSummary[];
  approvePatchSet: (patchSetId: string) => Promise<void>;
  rejectPatchSet: (patchSetId: string) => void;
  width: number;
  onResizeWidth: (value: number) => void;
  currentProject: ProjectSummary | undefined;
  updateDebugCommand: (debugCommand: string) => Promise<void>;
  debugRunning: boolean;
  startDebug: () => Promise<void>;
  stopDebug: () => Promise<void>;
};
export type SettingsPanelProps = {
  settingsOpen: boolean;
  setSettingsOpen: React.Dispatch<React.SetStateAction<boolean>>;
  labels: Record<string, string>;
  locale: Locale;
  settingsSearch: string;
  setSettingsSearch: (value: string) => void;
  filteredSections: SettingsSection[];
  settingsSection: string;
  setSettingsSection: (value: string) => void;
  sectionLabel: (section: SettingsSection) => string;
  activeSectionMeta: SettingsSection | undefined;
  settings: UiSettings;
  setSetting: (key: keyof UiSettings, value: unknown) => void;
  runtimeData: RuntimeStatus | null;
  activeProject: string | null;
  probeProfiles: () => Promise<void>;
  exportDiagnostics: () => void;
  resetLayout: () => void;
  resetAllSettings: () => void;
  bridge: BridgeApi | null;
  chooseDefaultProjectDirectory: () => Promise<void>;
};
