import type { Locale } from "@agentflow/localization";
import type { createTypedBridge } from "@agentflow/desktop-bridge";

export type PermissionDimensionsInput = Record<string, unknown>;
export type WorkflowPayload = Record<string, unknown> & {
  text?: string;
  permissionRequest?: Record<string, unknown>;
};
export type RuntimeStatus = Record<string, unknown> & {
  settings?: Record<string, unknown>;
  tasks?: Array<{ id: string; state?: string }>;
  conversations?: Array<{ id: string }>;
  runs?: Array<{ id: string; conversationId?: string; state?: string }>;
  events?: Array<{ conversationId?: string }>;
  projects?: Array<{ id: string; defaultBranch?: string }>;
  permissions?: Array<{ status?: string }>;
  resumeAvailableRunIds?: string[];
};
export type TimelineMessage = {
  id: string;
  role: string;
  text: string;
  streaming?: boolean;
  kind?: string;
  activity?: {
    category?: "tool" | "command" | "workflow";
    status?: string;
    title?: string;
    detail?: string;
  };
};
export type DiffViewerProps = {
  content: string;
  search: string;
  onSearch: (value: string) => void;
  viewMode: string;
  onViewMode: (value: string) => void;
  findings: Array<{ line?: number }>;
  locale: Locale;
};
export type PlanApprovalCardProps = {
  onApprove: () => void;
  onRequestChanges: () => void;
  onOpenPlan: () => void;
  labels: {
    planReady: string;
    requirements: string;
    tasks: string;
    structureChanges: string;
    yes: string;
    no: string;
    risk: string;
    openPlan: string;
    requestChanges: string;
    approveAndRun: string;
  };
  locale?: Locale;
  specification: { requirements: unknown[]; structureChanges: unknown[]; risk: string };
  tasks: Array<{ id: string; dependencyIds?: string[] }>;
};
export type PermissionRequest = {
  permission?: { requested?: string };
  permissionRequest?: PermissionRequest;
  requestedProfile?: string;
  command?: string;
  workingDirectory?: string;
  reason?: string;
};
export type PermissionRequestCardProps = {
  onResolve: (decision: string) => void;
  request?: PermissionRequest | null;
  locale?: Locale;
};
export type UiSettings = {
  theme: string;
  accent: string;
  language: string;
  workerCount: string;
  restoreWorkspace: boolean;
  confirmClose: boolean;
  autoProbe: boolean;
  manualModels: Array<{
    adapterId: string;
    providerId: string;
    modelId: string;
    name: string;
  }>;
  aiProviders: Array<{
    id: string;
    name: string;
    endpoint: string;
    apiKey: string;
    model?: string;
    models?: string[];
    apiVersion?: string;
  }>;
  defaultModelId?: string;
  recentLimit: string;
  defaultProjectDirectory: string;
  editor: string;
  density: string;
  uiTextSize: string;
  codeTextSize: string;
  timestampFormat: string;
  retries: string;
  planApproval: string;
  blockOnFailingValidation: boolean;
  requireIndependentReviewer: boolean;
  integrationPolicy: string;
  concurrencyLimit: string;
  allowRiskOverrides: boolean;
  requireApprovalNetwork: boolean;
  requireApprovalPackages: boolean;
  customPermissionDimensions: Record<string, unknown>;
  pushPolicy: string;
  inAppNotif: boolean;
  systemNotif: boolean;
  soundNotif: boolean;
  notifPlanApproval: boolean;
  notifAgentFailure: boolean;
  notifBlockedTask: boolean;
  notifReviewComplete: boolean;
  notifValidationComplete: boolean;
  notifIntegrationReady: boolean;
  retention: string;
  reducedMotion: boolean;
  highContrastFocus: boolean;
  screenReaderAnnouncements: boolean;
  inspectorWidth?: number;
};
export type RuntimeAdapterProfile = {
  id?: string;
  adapterId: string;
  name?: string;
  status?: string;
  version?: string;
  diagnostic?: string;
};
export type RuntimeModel = {
  id: string;
  adapterId: string;
  providerId?: string;
  providerModelId?: string;
  name: string;
  cliDefault?: boolean;
  verified?: boolean;
  capabilities?: string[];
};
export type SettingsRuntimeData = {
  adapterIds?: string[];
  profiles?: RuntimeAdapterProfile[];
  models?: RuntimeModel[];
  projects?: Array<{ id: string; defaultBranch?: string }>;
  dataDirectory?: string;
};
export type SettingsContentProps = {
  section: string;
  settings: UiSettings;
  set: (key: keyof UiSettings, value: unknown) => void;
  locale?: Locale;
  runtimeData?: SettingsRuntimeData | null;
  activeProject?: string;
  onProbe: () => void;
  onExportDiagnostics: () => void;
  onResetLayout: () => void;
  onResetSettings: () => void;
  onChooseDefaultProjectDirectory: () => void;
};
export type BridgeApi = ReturnType<typeof createTypedBridge>;
export type ComposerProps = {
  locale: Locale;
  openMenu: string | null;
  setOpenMenu: (value: string | null) => void;
  mode: string;
  setMode: (value: string) => void;
  permission: string;
  setPermission: (value: string) => void;
  currentModel: { id: string; label: string };
  model: string;
  modelGroups: Array<{
    id: string;
    label: string;
    models: Array<{
      id: string;
      label: string;
      sub: string;
      vision?: boolean;
      model: { providerModelId?: string };
    }>;
  }>;
  hasAuto: boolean;
  selectModel: (modelId: string) => void;
  contextAttachments: string[];
  setContextAttachments: React.Dispatch<React.SetStateAction<string[]>>;
  attachContextFiles: () => Promise<void>;
  composerRef: React.RefObject<HTMLTextAreaElement>;
  composerText: string;
  setComposerText: (value: string) => void;
  sendMessage: () => void;
  sending: boolean;
  stopActiveRun: () => Promise<void>;
  bridge: BridgeApi | null;
  runtimeConversationId: string | null;
  runtimeState: string;
  failedRunId: string | null;
  retryFailedRun: (resume: boolean) => Promise<void>;
  runtimeData: RuntimeStatus | null;
};
export type ConversationSidebarProps = {
  sidebarOpen: boolean;
  locale: Locale;
  labels: Record<string, string>;
  openMenu: string | null;
  toggleMenu: (name: string) => void;
  setOpenMenu: (value: string | null) => void;
  project?: { name?: string } | null;
  projectList: Array<{ id: string; name: string; branch?: string; convCount?: number }>;
  activeProject: string | null;
  setActiveProject: (id: string) => void | Promise<void>;
  openProject: () => Promise<void>;
  canOpenProject: boolean;
  openProjectUnavailableReason?: string;
  conversationSearchRef: React.RefObject<HTMLInputElement>;
  conversationQuery: string;
  setConversationQuery: (value: string) => void;
  newConversation: () => Promise<void>;
  conversationFilters: Array<[string, string, React.ComponentType<Record<string, unknown>> | null]>;
  conversationFilter: string;
  setConversationFilter: (value: string) => void;
  visibleConversations: Array<{
    id: string;
    title: string;
    pinned?: boolean;
    statusTone?: string;
    status?: string;
    time?: string;
  }>;
  runtimeConversationId: string | null;
  selectConversation: (id: string) => void;
  togglePinnedConversation: (id: string) => void;
  setSettingsOpen: (value: boolean) => void;
};
export type VirtualTimelineProps = {
  messages: TimelineMessage[];
  onCopy: (text: string) => Promise<void>;
  copyLabel?: string;
  jumpLabel?: string;
  timelineLabel?: string;
  locale?: Locale;
};
export type InspectorPanelProps = {
  inspectorOpen: boolean;
  tabs: string[];
  tab: string;
  setTab: React.Dispatch<React.SetStateAction<string>>;
  locale: Locale;
  bridge: BridgeApi | null;
  runtimeChangeRequestId: string | null;
  integrateApproved: () => Promise<void>;
  preparePullRequest: () => Promise<void>;
  workflowPhase: string;
  workflowProgress: number;
  completedTaskCount: number;
  displayTasks: any[];
  displayReviews: any[];
  currentModel: { id: string; label: string };
  effectivePermission: { id: string; label: string };
  currentChangeRequest: any;
  currentRoutingDecision: any;
  repositoryStatus: any;
  runtimeData: RuntimeStatus | null;
  runReadyTasks: () => Promise<void>;
  runTask: (taskId: string) => Promise<void>;
  displayRuns: any[];
  displayPatchSets: any[];
  artifactContent: { content?: string } | null;
  openArtifact: (artifactId: string) => Promise<void>;
  openArtifactId: string | null;
  runValidation: (patchSetId: string) => Promise<void>;
  startReview: (patchSetId: string) => Promise<void>;
  artifactLoading: boolean;
  artifactSearch: string;
  setArtifactSearch: (value: string) => void;
  artifactViewMode: string;
  setArtifactViewMode: (value: string) => void;
  displayFindings: any[];
  sendFindingsToFixer: () => void;
  blockingFindingsCount: number;
  patchSetsAwaitingReview: any[];
  approvePatchSet: (patchSetId: string) => Promise<void>;
  rejectPatchSet: (patchSetId: string) => void;
  width: number;
  onResizeWidth: (value: number) => void;
  currentProject: any;
  updateDebugCommand: (debugCommand: string) => Promise<void>;
  debugRunning: boolean;
  startDebug: () => Promise<void>;
  stopDebug: () => Promise<void>;
};
export type SettingsPanelProps = {
  settingsOpen: boolean;
  setSettingsOpen: React.Dispatch<React.SetStateAction<boolean>>;
  labels: Record<string, string>;
  locale: Locale;
  settingsSearch: string;
  setSettingsSearch: (value: string) => void;
  filteredSections: any[];
  settingsSection: string;
  setSettingsSection: (value: string) => void;
  sectionLabel: (section: any) => string;
  activeSectionMeta: any;
  settings: UiSettings;
  setSetting: (key: keyof UiSettings, value: unknown) => void;
  runtimeData: RuntimeStatus | null;
  activeProject: string | null;
  probeProfiles: () => Promise<void>;
  exportDiagnostics: () => void;
  resetLayout: () => void;
  resetAllSettings: () => void;
  bridge: BridgeApi | null;
  chooseDefaultProjectDirectory: () => Promise<void>;
};
